### ISSUE TITLE
redux store has items nested inside items

### ISSUE THREAD

**Issue by nigel5** [nigel5/octo-found#1]
Expected behaviour:
After an api call to fetch all items, the reducer handles the data and puts it into the store. The store's structure should look like this,

`items: [{_id: 1, . . . }, {_id: 2, . . . }, ... {_id: n}]
`

Actual behaviour:

```
items: {
    items: [{_id: 1, . . . }, {_id: 2, . . . }, ... {_id: n}]
}
```

**Comment by Lanahh** [comment]
check your reducer again, you used items which is your (const) variable, change it follow below
    case FETCH_ALL_ITEMS_SUCCESS:
      return {
        ...state,
         data: action.data
       };

**Comment by nigel5** [comment]
It turns out the issue was not due to the variable name being the same as the reducer name.
It was because the reducer nested them into another array. The upper level of the nest was from the rootReducer.

https://github.com/nigel5/octo-found/blob/043e14f1196b488f3175bbcad28fb55c65715d8a/src/reducers/index.js#L3-L5
